import { describe, it, expect, beforeEach } from "vitest";
import { IDBFactory } from "fake-indexeddb";
import { clearPovBleedLayers, type CrystallizedState } from "../src/inference/crystallized";
import { Repo } from "../src/storage/repo";
import { __resetDbForTests } from "../src/storage/db";

const state = (o: Partial<CrystallizedState>): CrystallizedState => ({
  schema: [], nodes: [], unreferencedPasses: {}, outlook: [], preferences: [], ...o,
});

const contaminated = () => state({
  // Knows is KEPT — it self-heals in place and is the expensive layer.
  schema: [{ subject: "Orario", text: "I know the city still lives by roads and trade." }],
  // These three were generated by the POV-unanchored prompt: the player's experiences, not the NPC's.
  nodes: [
    { id: "n1", vibrancy: 3, snapshot: "I woke in a ruined shrine where roots clung to the stones.", links: [] },
    { id: "n2", vibrancy: 2, snapshot: "Tartarus cracked open, and I felt the world tear sideways.", links: [] },
  ],
  outlook: [{ text: "The lower world endures through neglect.", strength: 2 }],
  preferences: [{ text: "I dislike the sound of chains.", strength: 1 }],
});

describe("clearPovBleedLayers (pure)", () => {
  it("clears Vivid/Outlook/Preferences, keeps Knows, and reports what it removed", () => {
    const { state: clean, changed, removed } = clearPovBleedLayers(contaminated());
    expect(changed).toBe(true);
    expect(clean.nodes).toEqual([]);
    expect(clean.outlook).toEqual([]);
    expect(clean.preferences).toEqual([]);
    // Knows survives untouched.
    expect(clean.schema).toEqual([{ subject: "Orario", text: "I know the city still lives by roads and trade." }]);
    // Everything removed is handed back so the caller can archive it.
    expect(removed.vivid).toHaveLength(2);
    expect(removed.vivid[0]).toContain("ruined shrine");
    expect(removed.outlook).toEqual(["The lower world endures through neglect."]);
    expect(removed.preferences).toEqual(["I dislike the sound of chains."]);
  });

  it("is a no-op on a state with nothing in those layers (changed=false, same reference)", () => {
    const s = state({ schema: [{ subject: "Rena", text: "a friend" }] });
    const res = clearPovBleedLayers(s);
    expect(res.changed).toBe(false);
    expect(res.state).toBe(s);
  });
});

describe("repo.healPovBleedCrystallizedState (DB heal v2)", () => {
  let repo: Repo;
  beforeEach(() => {
    (globalThis as any).indexedDB = new IDBFactory();
    __resetDbForTests();
    repo = new Repo();
  });

  it("clears the affected layers and archives every removed entry as 'perspective-heal'", async () => {
    await repo.putCrystallizedState("adv1", "hermes", contaminated());
    await repo.putCrystallizedState("adv1", "clean", state({ schema: [{ subject: "Rena", text: "a friend" }] }));

    expect(await repo.healPovBleedCrystallizedState()).toBe(1); // only the contaminated one

    const healed = await repo.getCrystallizedState("adv1", "hermes");
    expect(healed?.nodes).toEqual([]);
    expect(healed?.outlook).toEqual([]);
    expect(healed?.preferences).toEqual([]);
    expect(healed?.schema).toHaveLength(1); // Knows kept

    // Nothing destroyed — 2 vivid + 1 outlook + 1 preference recoverable from the archive.
    const archive = await repo.getCrystallizedArchive("adv1");
    expect(archive).toHaveLength(4);
    expect(archive.every((e) => e.reason === "perspective-heal")).toBe(true);
    expect(archive.filter((e) => e.kind === "vivid")).toHaveLength(2);
    expect(archive.filter((e) => e.kind === "outlook")).toHaveLength(1);
    expect(archive.filter((e) => e.kind === "preferences")).toHaveLength(1);
    expect(archive.map((e) => e.text)).toContain("I dislike the sound of chains.");
  });

  it("must NOT wipe layers rebuilt after the heal (why it stays version-stamp gated)", async () => {
    await repo.putCrystallizedState("adv1", "hermes", contaminated());
    await repo.healPovBleedCrystallizedState();

    // The fixed prompt regenerates a legitimate memory.
    const rebuilt = state({
      schema: [{ subject: "Orario", text: "kept" }],
      nodes: [{ id: "n9", vibrancy: 3, snapshot: "Syr smiled through the chaos as if the room were easy.", links: [] }],
    });
    await repo.putCrystallizedState("adv1", "hermes", rebuilt);

    // A second run WOULD destroy it — proving the stamp gate in ensureDbHealed is load-bearing.
    expect(await repo.healPovBleedCrystallizedState()).toBe(1);
    expect((await repo.getCrystallizedState("adv1", "hermes"))?.nodes).toEqual([]);
  });
});
