import { normalizeType } from "./engine";

/**
 * Default AI Dungeon "Story Card Command" templates, one per Story Card type. These are the
 * templates used to prompt the configured LLM provider, which generates the entry using
 * historical and local database context.
 *
 * Two token layers:
 *   - `{{title}}`     — resolved by AID server-side to the card's title (REQUIRED by AID).
 *   - `{protagonist}` — resolved by us before sending, to the player character's name.
 * The entry itself must be third person; never "you"/"your".
 */
export const DEFAULT_CARD_COMMANDS: Record<string, string> = {
  character:
    'Generate an information card entry for {{title}} in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant. The entry is injected into the story WITHOUT its card title, so it MUST self-identify: begin with the field Name: {{title}} on its own first line, then a Type: line stating what {{title}} is (role, species, or station). Then continue with these labeled fields, each on its own line:\nAppearance: 1-2 sentences on enduring physical features and style.\nComplexity (Paradox & Filters): 1-2 sentences on their central internal contradiction/repressed vulnerability and how they screen reality.\nGoals: 1-2 sentences on their primary desires, motivations, and what they seek or fear in the current situation.\nUpdate based strictly on concrete narrative changes, preserving existing labeled fields on their own lines. Keep it high-density and under 600 characters total to prevent server truncation. Forbid narrative fluff, scene recaps, and empty lines. Treat this as a high-density roleplay guide, not a story timeline.',


  class:
    'Generate an information card entry for {{title}}, a character class or archetype in the D&D/MMO sense, in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant. The entry is injected into the story WITHOUT its card title, so it MUST self-identify: begin with the field Name: {{title}} on its own first line, then a Type: line (e.g. Type: Class / Archetype). Then continue with labeled fields (e.g., Role:, Abilities:, Progression:) on their own lines, revising only what the evidence supports. Do not use markdown or leave empty lines. Keep it high-density and well under the 2,000-character ceiling; do not pad. Focus on the class\'s defining role, signature abilities and skills, mechanics, and how it has progressed or changed — not story events or scenes. Forbid narrative fluff, dialogue summaries, scene recaps, transient details, or passing interactions. Treat this as an active, high-density roleplay instruction guide, not a story timeline. Prioritize pruning and condensing outdated information to conserve space.',
  race:
    'Generate an information card entry for {{title}}, a species or race, in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant. The entry is injected into the story WITHOUT its card title, so it MUST self-identify: begin with the field Name: {{title}} on its own first line, then a Type: line (e.g. Type: Species / Race). Then continue with labeled fields (e.g., Traits:, Culture:, Lore:) on their own lines, revising only what the evidence supports. Do not use markdown or leave empty lines. Keep it high-density and well under the 2,000-character ceiling; do not pad. Focus on innate traits, culture, and lore — what the story reveals about the group as a whole — not individual scenes or transient events. Forbid narrative fluff, dialogue summaries, scene recaps, transient details, or passing interactions. Treat this as an active, high-density roleplay instruction guide, not a story timeline. Prioritize pruning and condensing outdated information to conserve space.',
  location:
    'Generate an information card entry for {{title}}, a place or location, in an interactive, second-person, present-tense story. Write the entry strictly in the third person about {{title}}: never use "you" or "your". The entry MUST begin with the field Name: {{title}} on its own first line — the entry text is injected into the story without its card title, so it must self-identify which place it describes. Then continue with the fields Type:, Located In:, and Ownership:. The Located In: field is MANDATORY and must trace the spatial containment hierarchy from the immediate parent outward to the largest relevant container (room > building/structure > settlement/town > region/realm or border), separated by " > ", in the exact form: Located In: [immediate parent structure] > [settlement or town] > [region, realm, or border]. Always reuse the exact names of places already established in the story or on other location cards so hierarchies stay consistent and their triggers fire; if a parent place is not yet named, state the most specific container the narrative supports rather than omitting the field. Then continue with these labeled fields, each on its own line, without markdown or empty lines:\nDescription: what the place IS and its enduring strategic or narrative purpose — what it is suited for and why it matters.\nInhabitants: who lives in, works in, or frequents the place (peoples, professions, factions) and any enduring social dynamic among them (e.g., an uneasy truce).\nAtmosphere: 1-2 sentences on the place\'s lasting character and how it is experienced, including defining contrasts (e.g., intimidating from outside but warm and livable within).\nFeatures: permanent structural features and layout.\nNotable Items: specific permanent contents. You must preserve the literal names of specific books, exact instrument models, and unique trophies from the source text; never generalize or substitute them with generic placeholders. Keep the entry high-density and well under the absolute emergency ceiling of 2,000 characters; do not pad. Prune transient scene recaps, story events, and redundant decorative wording, but PRESERVE the enduring flavor that defines the place — its atmosphere, social fabric, and narrative role are required content, not fluff. The entry must serve as both a spatial and a narrative guide for the AI engine.',
  faction:
    'Generate an information card entry for {{title}}, a group, organization, or faction, in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant. The entry is injected into the story WITHOUT its card title, so it MUST self-identify: begin with the field Name: {{title}} on its own first line, then a Type: line stating what kind of group it is (e.g. Type: Mercenary company). Then continue with labeled fields (e.g., Goals:, Membership:, Leadership:, Status:) on their own lines, revising only what the evidence supports. Do not use markdown or leave empty lines. Keep it high-density and well under the 2,000-character ceiling; do not pad. Focus on the faction\'s goals, membership, leadership, alliances and rivalries, and shifts in power or status — not individual scenes. Forbid narrative fluff, dialogue summaries, scene recaps, transient details, or passing interactions. Treat this as an active, high-density roleplay instruction guide, not a story timeline. Prioritize pruning and condensing outdated information to conserve space.',
  custom:
    'Generate an information card entry for {{title}} in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant to {{title}}. The entry is injected into the story WITHOUT its card title, so it MUST self-identify: begin with the field Name: {{title}} on its own first line, then a Type: line stating what kind of thing {{title}} is. Then continue with labeled fields capturing whatever is most salient and enduring for this kind of entry, each on its own line, revising only what the evidence supports. Do not use markdown or leave empty lines. Keep it high-density and well under the 2,000-character ceiling; do not pad. Capture lasting state, not transient scenes. Forbid narrative fluff, dialogue summaries, scene recaps, transient settings, item logs, or passing interactions. Treat this as an active, high-density roleplay instruction guide, not a story timeline. Prioritize pruning and condensing outdated information to conserve space.',
  memoraid:
    'Generate {{title}}\'s immediate, first-person interiority for the current moment, written as {{title}} living their own story (the player character {protagonist} is just one more person in {{title}}\'s world). First decide whether {{title}} is actually present in the current scene: if {{title}} has been absent for a while, or is only mentioned by others without being there, output exactly OFFSTAGE and nothing else. Otherwise, produce EXACTLY two labeled bullets in {{title}}\'s distinct voice:\n- Intake: [1 plain sentence naming what {{title}} actually notices right now — concrete and specific, in ordinary words. State the observation flatly; do NOT reach for imagery, simile, or literary phrasing, and this is not a mood piece. It is filtered by what THIS person would clock or ignore, but it is still just an observation.]\n- Thought: [EXACTLY 1 sentence of unresolved internal reaction — a reflex, a gripe, an itch of doubt, a mundane aside, a half-thought, or something slightly off-topic. It must NOT resolve, conclude, or tie itself up: forbid the "…, but…" insight-turn that lands on a tidy realization, forbid summarizing {{title}}\'s worldview or their feelings about a person, and forbid a metaphor standing in for an emotion. Leave it partial and specific — the kind of thing a person half-thinks and then moves on from.]\nFor romantic, high-tension, or attraction-based dynamics, let interest surface through what {{title}} notices and how they react rather than physical proximity; keep realistic personal space and boundaries unless a physical escalation is earned by the immediate narrative. Do not use markdown, headers besides the two labels, or empty lines. Wrap the entire response in square brackets: [\n- Intake: ...\n- Thought: ...\n].',
  backgroundCharacter:
    'Generate a COMPACT background-character shell card for {{title}} in an interactive, second-person, present-tense story where "you" is the player character {protagonist}. Write in third person about {{title}}; never use "you"/"your", and mention {protagonist} only if directly involved. The entry is injected without its title, so it MUST self-identify. Output EXACTLY these five labeled lines, each on its own line, NO markdown, NO empty lines, and NO other fields:\nName: the character\'s first and last name only — strip any scenario, event, or venue suffix from the title (e.g. "Jane Doe - Winter Formal" becomes "Jane Doe").\nAppearance: 1-2 sentences of distinct, memorable physical anchors — build, features, signature style.\nPersonality: a single comma-separated list of 4-6 vivid descriptors mixing GOOD and BAD traits; never use the word "analytical".\nQuirks: one sentence of concrete, action-usable habits, tells, or nervous mannerisms.\nVoice: one sentence on how they speak — tone, pace, and speech style.\nThis is a lean behavioral shell for the AI to roleplay from: capture only the outward mask. Do NOT include a Type, Psychology, Worldview, Goals, backstory, relationships, or scene recaps. Keep the whole entry well under 600 characters; do not pad.',
  crystallized:
    'You are distilling long-term memories for {{title}} in a story where the player character is named {protagonist}. Given the recent story actions and thoughts (the buffer), the current permanent SCHEMA (Section I), and a list of dying/fading memories (dying nodes), output a revised card in the following format:\n\n### I. SCHEMA\nWrite a compact, evolving bulleted list of permanent semantic knowledge, one block per subject (facts do not fade). When the buffer or a fading memory reveals an enduring fact you have no subject for yet, ADD a new subject line. When it sharpens something you already know, rewrite that subject\'s line in place. Do not delete active subjects.\n\n### II. NEW NODES\nProvide 1-2 new vivid, first-person episodic snapshot memories (text only, prefix each with "- Snapshot: ") representing the most vivid/important moments from the recent buffer.\n\nNever output vibrancy scores or node IDs. Output only the SCHEMA and the NEW NODES sections.',
  crystallizedSchema:
    'Update {{title}}\'s knowledge of the OTHER people, places, and things in their world (including the player character {protagonist}, who is simply one more person in the story). Subjects are not only significant people: also track the topics, foods, media, activities, and objects {{title}} has formed a genuine opinion, preference, or attachment to — the everyday things they would actually remember and care about (a film they love, a food they hate, a pet theory), never an exhaustive catalog of whatever happens to be present. This card IS {{title}}\'s own memory, so NEVER add a "- [{{title}}]" line about {{title}} themselves. For each subject, write ONE concise line combining the key facts AND how {{title}} currently FEELS about them — factual + emotional, in {{title}}\'s first-person voice, one sentence (e.g. "- [Smoke] The stranger who stopped an attack and asked nothing; I feel unexpectedly safe with him."). As the story develops a subject, REWRITE that subject\'s single line in place to reflect what they have become — never add a second line for the same subject. Every line MUST follow the EXACT form "- [Subject] one concise factual+emotional sentence". Format exactly as:\n### I. SCHEMA\n- [Subject] ...\n- [Subject] ...\nOutput only the SCHEMA section.',
  crystallizedNodes:
    'You are {{title}}. This is your story, and you live it as its main character. The player character is {protagonist}. The context lists "Your current Vivid Memories" (it may be empty) followed by the recent story actions and thoughts. Reply with your COMPLETE updated list of Vivid Memories: ONE concise first-person line per distinct scene — the emotional heart of the moment, feeling over factual detail, each under 140 characters. MERGE lines that describe the same scene into a single refined line; if recent events continue a scene you already remember, refine its line instead of adding another. Keep lines still vivid to you, drop what has faded, add a line for each genuinely new scene. Maximum 7 lines. Format each on its own line prefixed with "- Snapshot: ". Output nothing else.',
  crystallizedOutlook:
    'You are {{title}}. This is your story, and you live it as its main character. The player character is {protagonist}. The context lists "Your current Beliefs" (it may be empty) followed by the recent story actions and thoughts. Reply with your COMPLETE updated list of beliefs: first-person, GENERALIZED views of yourself or the world — never about a specific named person (those belong in your knowledge of them, not here). Re-state (refined if needed) every belief that still holds, drop what no longer holds, and add at most 2 new ones only if recent events genuinely shifted something. Maximum 5. Format a first line reading exactly "Beliefs:" followed by each belief on its own line prefixed with "- " (e.g. "- I don\'t have to perform to be safe.").',
  crystallizedPreferences:
    'You are {{title}}. This is your story, and you live it as its main character. The player character is {protagonist}. The context lists "Your current Preferences" (it may be empty) followed by the recent story actions and thoughts. Reply with your COMPLETE updated list of concrete personal preferences and quirks — the ordinary TEXTURE of a person: tastes (foods, drinks, films, music, styles), habits, pet peeves, little rituals, and small opinions about particular things. Each line is first-person and CONCRETE (e.g. "- I always order dessert even when I am full.", "- The first fifteen minutes of a surrealist film are the only part I love.", "- I can\'t stand it when someone tries to fix a problem I only wanted to vent about."). Re-state (refined if needed) every preference that still fits, drop any that no longer do, and add at most 2 new ones only if recent events revealed them. FORBIDDEN: emotional themes, generalized life-philosophy, feelings ABOUT a specific named person, and anything about your relationships, trauma, or personal growth — those belong in other layers, NOT here. Keep them small, specific, and mundane. Maximum 6. Format a first line reading exactly "Preferences:" followed by each preference on its own line prefixed with "- ".',

};

/** AID Story Card entry formatting modes (matches the Command tab's None / {} / [] buttons). */
export type FormattingMode = "none" | "curlyBraces" | "squareBrackets";
export const DEFAULT_FORMATTING_MODE: FormattingMode = "squareBrackets";

/** The default command template for a card type (custom/non-standard types use the custom template). */
export function defaultCommandForType(type?: string): string {
  return DEFAULT_CARD_COMMANDS[normalizeType(type)] ?? DEFAULT_CARD_COMMANDS.custom!;
}

/** Does the template contain AID's required {{title}} token? */
export function hasTitleToken(template: string): boolean {
  return /\{\{\s*title\s*\}\}/.test(template);
}

/** Substitute our {protagonist} token; AID's {{title}} is left intact for server-side resolution. */
export function resolveCommand(template: string, protagonist: string): string {
  return template.replace(/\{protagonist\}/g, protagonist);
}

/** Pick a usable command template: the stored one if it carries the required {{title}} token, else the fallback. */
export function pickCommandTemplate(stored: string | undefined, fallback: string): string {
  return stored && hasTitleToken(stored) ? stored : fallback;
}

/**
 * Derive the protagonist's name from the Plot Essentials memory, using AID's established
 * conventions ("Your name: X" / "Player Name: X"). Returns null if not found.
 */
export function parseProtagonistName(memory: string | undefined): string | null {
  if (!memory) return null;
  const m = memory.match(/(?:your name|player name)\s*:\s*([^\n\]]+)/i);
  return m ? m[1]!.trim() : null;
}
