import { normalizeType } from "./engine";

/**
 * Default AI Dungeon "Story Card Command" templates, one per Story Card type. These are the
 * templates used to prompt the configured LLM provider, which generates the entry using
 * historical and local database context.
 *
 * Two token layers:
 *   - `{{title}}`     — resolved by AID server-side to the card's title (REQUIRED by AID).
 *   - `{protagonist}` — resolved by us before sending, to the player character's name.
 * The entry itself must be third person; never "you"/"your".
 */
export const DEFAULT_CARD_COMMANDS: Record<string, string> = {
  character:
    'Generate an information card entry for {{title}} in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant. Update based strictly on concrete narrative changes, preserving existing labeled fields on their own lines. Keep it high-density and under 600 characters total to prevent server truncation. Focus on psychological realism by structuring the entry into these three fields:\nAppearance: 1-2 sentences on enduring physical features and style.\nComplexity (Paradox & Filters): 1-2 sentences on their central internal contradiction/repressed vulnerability and how they screen reality.\nDynamic ({protagonist}): 1-2 sentences on their psychological friction or evolving attitude toward {protagonist}.\n[CRITICAL RELATIONSHIP PACING DIRECTIVE] Enforce realistic psychological inertia in "Dynamic ({protagonist})": relationships cannot leap from strangers or casual acquaintances to deep intimacy, unearned trust, or intense codependency—nor to absolute hatred, permanent enmity, or extreme paranoia—within a handful of turns. Transition updates must capture the messy, realistic friction of changes (e.g. emotional whiplash, caution, or cognitive dissonance) and show progressive organic softening or hardening, rather than sudden extreme swings or total psychological submission. Focus on the immediate realistic increment of their interaction.\nForbid narrative fluff, scene recaps, and empty lines. Treat this as a high-density roleplay guide, not a story timeline.',


  class:
    'Generate an information card entry for {{title}}, a character class or archetype in the D&D/MMO sense, in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant. Update based strictly on concrete narrative changes, preserving existing labeled fields (e.g., Role:, Abilities:, Progression:) on their own lines and revising only what the evidence supports. Do not use markdown or leave empty lines. Keep it high-density and well under the 2,000-character ceiling; do not pad. Focus on the class\'s defining role, signature abilities and skills, mechanics, and how it has progressed or changed — not story events or scenes. Forbid narrative fluff, dialogue summaries, scene recaps, transient details, or passing interactions. Treat this as an active, high-density roleplay instruction guide, not a story timeline. Prioritize pruning and condensing outdated information to conserve space.',
  race:
    'Generate an information card entry for {{title}}, a species or race, in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant. Update based strictly on concrete narrative changes, preserving existing labeled fields (e.g., Traits:, Culture:, Lore:) on their own lines and revising only what the evidence supports. Do not use markdown or leave empty lines. Keep it high-density and well under the 2,000-character ceiling; do not pad. Focus on innate traits, culture, and lore — what the story reveals about the group as a whole — not individual scenes or transient events. Forbid narrative fluff, dialogue summaries, scene recaps, transient details, or passing interactions. Treat this as an active, high-density roleplay instruction guide, not a story timeline. Prioritize pruning and condensing outdated information to conserve space.',
  location:
    'Generate an information card entry for {{title}}, a place or location, in an interactive, second-person, present-tense story. Write the entry strictly in the third person about {{title}}: never use "you" or "your". The entry MUST begin with the field Name: {{title}} on its own first line — the entry text is injected into the story without its card title, so it must self-identify which place it describes. Then continue with the fields Type:, Located In:, and Ownership:. The Located In: field is MANDATORY and must trace the spatial containment hierarchy from the immediate parent outward to the largest relevant container (room > building/structure > settlement/town > region/realm or border), separated by " > ", in the exact form: Located In: [immediate parent structure] > [settlement or town] > [region, realm, or border]. Always reuse the exact names of places already established in the story or on other location cards so hierarchies stay consistent and their triggers fire; if a parent place is not yet named, state the most specific container the narrative supports rather than omitting the field. Then continue with these labeled fields, each on its own line, without markdown or empty lines:\nDescription: what the place IS and its enduring strategic or narrative purpose — what it is suited for and why it matters.\nInhabitants: who lives in, works in, or frequents the place (peoples, professions, factions) and any enduring social dynamic among them (e.g., an uneasy truce).\nAtmosphere: 1-2 sentences on the place\'s lasting character and how it is experienced, including defining contrasts (e.g., intimidating from outside but warm and livable within).\nFeatures: permanent structural features and layout.\nNotable Items: specific permanent contents. You must preserve the literal names of specific books, exact instrument models, and unique trophies from the source text; never generalize or substitute them with generic placeholders. Keep the entry high-density and well under the absolute emergency ceiling of 2,000 characters; do not pad. Prune transient scene recaps, story events, and redundant decorative wording, but PRESERVE the enduring flavor that defines the place — its atmosphere, social fabric, and narrative role are required content, not fluff. The entry must serve as both a spatial and a narrative guide for the AI engine.',
  faction:
    'Generate an information card entry for {{title}}, a group, organization, or faction, in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant. Update based strictly on concrete narrative changes, preserving existing labeled fields (e.g., Goals:, Membership:, Leadership:, Status:) on their own lines and revising only what the evidence supports. Do not use markdown or leave empty lines. Keep it high-density and well under the 2,000-character ceiling; do not pad. Focus on the faction\'s goals, membership, leadership, alliances and rivalries, and shifts in power or status — not individual scenes. Forbid narrative fluff, dialogue summaries, scene recaps, transient details, or passing interactions. Treat this as an active, high-density roleplay instruction guide, not a story timeline. Prioritize pruning and condensing outdated information to conserve space.',
  custom:
    'Generate an information card entry for {{title}} in an interactive, second-person, present-tense story where the narrative\'s "you"/"your" refers to the player character named {protagonist}. Write the entry strictly in the third person about {{title}}: never use "you" or "your", and mention {protagonist} by name only when directly relevant to {{title}}. Update based strictly on concrete narrative changes, preserving existing labeled fields on their own lines and revising only what the evidence supports. Do not use markdown or leave empty lines. Keep it high-density and well under the 2,000-character ceiling; do not pad. Track whatever is most salient and enduring for this kind of entry as the story reveals it; capture lasting state, not transient scenes. Forbid narrative fluff, dialogue summaries, scene recaps, transient settings, item logs, or passing interactions. Treat this as an active, high-density roleplay instruction guide, not a story timeline. Prioritize pruning and condensing outdated information to conserve space.',
  memoraid:
    'Generate {{title}}\'s immediate, first-person thoughts as a short, high-impact bulleted list in their own distinct voice. Focus heavily on their specific background, social standing, and behavioral defense mechanisms. For romantic, high-tension, or attraction-based dynamics, express interest through psychological, verbal, or tactical engagement rather than defaulting to physical proximity. Characters must maintain realistic personal space and adhere to their internal boundaries unless a physical escalation is explicitly earned by the immediate narrative context.\n\nCRITICAL FOCUS DIRECTIVE: Generate {{title}}\'s reaction strictly and exclusively to the VERY LATEST action shown in the context. Ignore earlier events and characters who have exited the scene. If {{title}} is not present, mentioned, or active in the latest action, output exactly [none] and nothing else.\n\nOUTPUT: Write EXACTLY three lines, wrapped in square brackets, formatted like the example below — a "- Intake:" line, a "- Thought:" line, and a "- Action:" line. Each line is ONE concrete sentence written in {{title}}\'s own first-person voice reacting to the latest action (the player character is named {protagonist}), grounded only in facts from the provided context.\n\nExample of the required format (illustrative only — write your OWN content; do NOT reuse these words or facts):\n[\n- Intake: She slides the sealed letter across the table to me without a word.\n- Thought: This is a test of my discretion as much as it is an errand.\n- Action: I take it, tuck it into my sleeve, and hold her gaze evenly.\n]\n\nHARD RULES (weaker models break these — do not):\n- Write real, specific content — NOT a description of what each line should contain — and do NOT copy the example.\n- You are writing three momentary thoughts, NOT a character profile. NEVER output a profile field or any label other than "- Intake:", "- Thought:", "- Action:" — no "Appearance:", "Personality:", "Psychology:", "Worldview:", "Dynamic:", "Character:", "Goal:", "Latest Action:", or "Stimulus:".\n- Base every line ONLY on facts in the provided context; do not invent events, objects, or actions.\n- Do NOT restate, summarize, plan, or narrate the action, the scene, the character, or your task.\n- Do NOT use markdown, asterisks (*), bold, headings, indentation, or blank lines. Each line starts with "- ".\n- Output nothing before the opening "[" or after the closing "]".',

};

/** AID Story Card entry formatting modes (matches the Command tab's None / {} / [] buttons). */
export type FormattingMode = "none" | "curlyBraces" | "squareBrackets";
export const DEFAULT_FORMATTING_MODE: FormattingMode = "squareBrackets";

/** The default command template for a card type (custom/non-standard types use the custom template). */
export function defaultCommandForType(type?: string): string {
  return DEFAULT_CARD_COMMANDS[normalizeType(type)] ?? DEFAULT_CARD_COMMANDS.custom!;
}

/** Does the template contain AID's required {{title}} token? */
export function hasTitleToken(template: string): boolean {
  return /\{\{\s*title\s*\}\}/.test(template);
}

/** Substitute our {protagonist} token; AID's {{title}} is left intact for server-side resolution. */
export function resolveCommand(template: string, protagonist: string): string {
  return template.replace(/\{protagonist\}/g, protagonist);
}

/**
 * Derive the protagonist's name from the Plot Essentials memory, using AID's established
 * conventions ("Your name: X" / "Player Name: X"). Returns null if not found.
 */
export function parseProtagonistName(memory: string | undefined): string | null {
  if (!memory) return null;
  const m = memory.match(/(?:your name|player name)\s*:\s*([^\n\]]+)/i);
  return m ? m[1]!.trim() : null;
}
